version: "3.9"

services:
  api:
    image: fromzero2ai_api
    env_file: api.env
    environment: 
      - LOG__LEVEL=debug
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - 9000:8070
  
  streamlit_app:
    image: fromzero2ai_app
    environment: 
      - LOG__LEVEL=debug
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit_app
    ports:
      - 8501:8501
  